CREATE TABLE [dbo].[InsertFakpol2] (

	[IdFakpol] varchar(8000) NULL, 
	[DealerCategory] varchar(8000) NULL, 
	[KodeOutlet] varchar(8000) NULL, 
	[OutletName] varchar(8000) NULL, 
	[InvoiceDate] date NULL, 
	[InvoiceNo] bigint NULL, 
	[CustomerName] varchar(8000) NULL, 
	[KTP] varchar(8000) NULL, 
	[TDP] varchar(8000) NULL, 
	[Alamat] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[TanggalPengajuanFakpol] datetime2(6) NULL, 
	[NoPengajuanFakpol] varchar(8000) NULL, 
	[CreatedDate] date NULL, 
	[ApprovalDate] date NULL, 
	[PrintedDate] varchar(8000) NULL, 
	[TglFakpol] date NULL, 
	[NoFakpol] varchar(8000) NULL, 
	[StatusFakpol] varchar(8000) NULL, 
	[NamaFakpol] varchar(8000) NULL, 
	[AlamatFakpol] varchar(8000) NULL, 
	[CityFakpol] varchar(8000) NULL, 
	[KecamatanFakpol] varchar(8000) NULL, 
	[KelurahanFakpol] varchar(8000) NULL, 
	[KodePosFakpol] varchar(8000) NULL, 
	[Email] varchar(8000) NULL, 
	[Color] varchar(8000) NULL, 
	[ChassisNumber] varchar(8000) NULL, 
	[EngineNumber] varchar(8000) NULL
);