CREATE TABLE [dbo].[InventTrans_Import202304] (

	[Item_number] float NULL, 
	[Physical_date] datetime2(6) NULL, 
	[Financial_date] datetime2(6) NULL, 
	[Reference] varchar(8000) NULL, 
	[Number] varchar(8000) NULL, 
	[Receipt] varchar(8000) NULL, 
	[Issue] varchar(8000) NULL, 
	[Quantity] float NULL, 
	[Unit] varchar(8000) NULL, 
	[CW_quantity] float NULL, 
	[CW_unit] varchar(8000) NULL, 
	[Financial_cost_amount] float NULL, 
	[Cost_amount] float NULL, 
	[Adjustment] float NULL, 
	[Created_by] varchar(8000) NULL, 
	[Created_date_and_time] datetime2(6) NULL, 
	[Device_number] varchar(8000) NULL, 
	[Physical_cost_amount] float NULL, 
	[Financial_voucher] varchar(8000) NULL, 
	[Physical_voucher] varchar(8000) NULL, 
	[Serial_number] varchar(8000) NULL, 
	[Batch_number] varchar(8000) NULL, 
	[Modified_date_and_time] datetime2(6) NULL, 
	[Site] varchar(8000) NULL, 
	[Project_ID] varchar(8000) NULL, 
	[Device_number_legacy] varchar(8000) NULL, 
	[Financial_date2] datetime2(6) NULL, 
	[Reference2] varchar(8000) NULL, 
	[Lot_ID] varchar(8000) NULL, 
	[Adjustment_number] varchar(8000) NULL, 
	[Physical_date2] datetime2(6) NULL
);