CREATE TABLE [dbo].[report_58_20250104] (

	[Tgl Unit Entry] datetime2(6) NULL, 
	[Tgl SIKK] datetime2(6) NULL, 
	[WONumber] varchar(8000) NULL, 
	[Status WO] varchar(8000) NULL, 
	[PKB Date] datetime2(6) NULL, 
	[Device Number] varchar(8000) NULL, 
	[No Polisi] varchar(8000) NULL, 
	[Customer Account] varchar(8000) NULL, 
	[Customer Name] varchar(8000) NULL, 
	[NPWP] varchar(8000) NULL, 
	[Phone] varchar(8000) NULL, 
	[Alamat] varchar(8000) NULL, 
	[Site] varchar(8000) NULL, 
	[Outlet] varchar(8000) NULL, 
	[Item number] varchar(8000) NULL, 
	[Product Name] varchar(8000) NULL, 
	[Warehouse] varchar(8000) NULL, 
	[Location] varchar(8000) NULL, 
	[Quantity] float NULL, 
	[LineProperty] varchar(8000) NULL, 
	[Line Status] varchar(8000) NULL, 
	[Receipt Date Requested] datetime2(6) NULL, 
	[Category] varchar(8000) NULL, 
	[Unit] varchar(8000) NULL, 
	[Sales price] float NULL, 
	[Discount] float NULL, 
	[Discount persen] float NULL, 
	[PPN] float NULL, 
	[Net Amount] float NULL, 
	[stdcost] float NULL, 
	[Product Name 2] varchar(8000) NULL, 
	[BU] varchar(8000) NULL, 
	[Resource] varchar(8000) NULL, 
	[Resource name] varchar(8000) NULL, 
	[WOGroup] varchar(8000) NULL, 
	[WODescription] varchar(8000) NULL, 
	[InvoiceID] varchar(8000) NULL, 
	[InvoiceAccount] varchar(8000) NULL, 
	[Invoice Date] datetime2(6) NULL, 
	[Voucher] varchar(8000) NULL, 
	[KM] float NULL, 
	[Engine number] varchar(8000) NULL, 
	[Vehicle Type Name] varchar(8000) NULL, 
	[Vehicle Model Name] varchar(8000) NULL, 
	[Vehicle Color Name] varchar(8000) NULL, 
	[Vehicle Year] int NULL, 
	[Vehicle Group Name] varchar(8000) NULL, 
	[CreatedBy] varchar(8000) NULL, 
	[MinorGroup] varchar(8000) NULL, 
	[MajorGroup] varchar(8000) NULL, 
	[MaskingName] varchar(8000) NULL, 
	[RecordId] bigint NULL, 
	[posted] varchar(8000) NULL, 
	[LastUpdated] datetime2(6) NULL
);