CREATE TABLE [dbo].[report_11] (

	[dealer] varchar(8000) NULL, 
	[nama_dealer] varchar(8000) NULL, 
	[outlet] varchar(8000) NULL, 
	[nama_outlet] varchar(8000) NULL, 
	[Area] varchar(8000) NULL, 
	[Group_Dealer] varchar(8000) NULL, 
	[tgl_invoice] datetime2(6) NULL, 
	[kode_customer] varchar(8000) NULL, 
	[nama_customer] varchar(8000) NULL, 
	[nama_tipe] varchar(8000) NULL, 
	[cv_lcv] varchar(8000) NULL, 
	[cara_bayar] varchar(8000) NULL, 
	[kode_leasing] varchar(8000) NULL, 
	[nama_leasing] varchar(8000) NULL, 
	[jumlah_total] float NULL, 
	[jumlah_cash] float NULL, 
	[jumlah_leasing] float NULL, 
	[series] varchar(8000) NULL, 
	[tipe_leasing] varchar(8000) NULL, 
	[TL_ID] int NULL, 
	[Leasing_Group] varchar(8000) NULL, 
	[jenis_customer] varchar(8000) NULL, 
	[segmen_description] varchar(8000) NULL, 
	[AccountNum] varchar(8000) NULL, 
	[Last_Update] datetime2(6) NULL, 
	[MaskingName] varchar(8000) NULL
);