CREATE TABLE [dbo].[report_34_combine] (

	[Customer_ID] varchar(8000) NULL, 
	[customer_Name] varchar(8000) NULL, 
	[SO/PKB_no] varchar(8000) NULL, 
	[PKB_no] varchar(8000) NULL, 
	[SalesOrderPoolId] varchar(8000) NULL, 
	[invoiceID] varchar(8000) NULL, 
	[SO/PKB_Date] date NULL, 
	[Tipe] varchar(8000) NULL, 
	[ItemGroupID] varchar(8000) NULL, 
	[part_number] varchar(8000) NULL, 
	[Part_Name] varchar(8000) NULL, 
	[SalesQty] bigint NULL, 
	[Qty] bigint NULL, 
	[amount] bigint NULL, 
	[Invoice_Date] date NULL, 
	[Kode_dealer] varchar(8000) NULL, 
	[Dealer] varchar(8000) NULL, 
	[Kode_Outlet] varchar(8000) NULL, 
	[Outlet] varchar(8000) NULL, 
	[Area] varchar(8000) NULL, 
	[Remarks] varchar(8000) NULL, 
	[LastUpdate] datetime2(6) NULL, 
	[DealerCategory] varchar(8000) NULL, 
	[MaskingName] varchar(8000) NULL
);