CREATE TABLE [dbo].[Report_31_202202] (

	[customer_id] varchar(8000) NULL, 
	[InvoiceId] varchar(8000) NULL, 
	[nama_customer] varchar(8000) NULL, 
	[SO/PKB_No] varchar(8000) NULL, 
	[SO/PKB_Date] datetime2(6) NULL, 
	[PO_No] varchar(8000) NULL, 
	[PO_Date] datetime2(6) NULL, 
	[Series] varchar(8000) NULL, 
	[Itemgroupid] varchar(8000) NULL, 
	[part_number] varchar(8000) NULL, 
	[part_name] varchar(8000) NULL, 
	[Qty_order] float NULL, 
	[Qty_Supply] float NULL, 
	[invoice_date] datetime2(6) NULL, 
	[nTOP] varchar(8000) NULL, 
	[persen_diskon] float NULL, 
	[Amount] float NULL, 
	[COGS] float NULL, 
	[GP] float NULL, 
	[Tipe] varchar(8000) NULL, 
	[Category] varchar(8000) NULL, 
	[Area] varchar(8000) NULL, 
	[Dealer] varchar(8000) NULL, 
	[nama_dealer] varchar(8000) NULL, 
	[Outlet] varchar(8000) NULL, 
	[nama_outlet] varchar(8000) NULL, 
	[Last_update] datetime2(6) NULL
);