CREATE TABLE [dbo].[temp_DirPartyPostalAddressView] (

	[_RecId_LogisticsPostalAddress] bigint NULL, 
	[_recVersion_LogisticsPostalAddress] int NULL, 
	[Address] varchar(8000) NULL, 
	[BuildingCompliment] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[CityRecId] bigint NULL, 
	[CountryCurrencyCode] varchar(8000) NULL, 
	[CountryRegionId] varchar(8000) NULL, 
	[County] varchar(8000) NULL, 
	[District] bigint NULL, 
	[IsLocationOwner] varchar(8000) NULL, 
	[IsPrimary] varchar(8000) NULL, 
	[IsPrimaryTaxRegistration] varchar(8000) NULL, 
	[IsPrivate] varchar(8000) NULL, 
	[Latitude] float NULL, 
	[Location] bigint NULL, 
	[LocationName] varchar(8000) NULL, 
	[Longitude] float NULL, 
	[Party] bigint NULL, 
	[PartyLocation] bigint NULL, 
	[PostBox] varchar(8000) NULL, 
	[PrivateForParty] bigint NULL, 
	[Street] varchar(8000) NULL, 
	[StreetNumber] varchar(8000) NULL, 
	[TimeZone] varchar(8000) NULL, 
	[ValidFrom] datetime2(6) NULL, 
	[ValidTo] datetime2(6) NULL, 
	[ModifiedDate] datetime2(6) NULL, 
	[RecordId] bigint NULL, 
	[State] varchar(8000) NULL, 
	[ZIPCodePublic] varchar(8000) NULL, 
	[Last_update] datetime2(6) NULL
);