CREATE TABLE [dbo].[temp_PersonPrivateDetails] (

	[Age] int NULL, 
	[BirthDate] datetime2(6) NULL, 
	[CitizenshipCountryRegion] varchar(8000) NULL, 
	[CreatedDateTime1] datetime2(6) NULL, 
	[DeceasedDate] datetime2(6) NULL, 
	[DisabledVerificationDate] datetime2(6) NULL, 
	[Education] varchar(8000) NULL, 
	[EthnicOrigin] bigint NULL, 
	[FatherBirthCountryRegion] varchar(8000) NULL, 
	[Gender] varchar(8000) NULL, 
	[IsDisabled] varchar(8000) NULL, 
	[IsFulltimeStudent] varchar(8000) NULL, 
	[ModifiedDateTime1] datetime2(6) NULL, 
	[MotherBirthCountryRegion] varchar(8000) NULL, 
	[NationalityCountryRegion] varchar(8000) NULL, 
	[NativeLanguage] bigint NULL, 
	[Person] bigint NULL, 
	[PersonBirthCity] varchar(8000) NULL, 
	[PersonBirthCountryRegion] varchar(8000) NULL, 
	[RecordId] bigint NULL, 
	[ZBloodType] varchar(8000) NULL, 
	[ZEducationLevel] varchar(8000) NULL, 
	[ZHobby] varchar(8000) NULL, 
	[ZReligion] varchar(8000) NULL, 
	[Last_update] datetime2(6) NULL
);