CREATE TABLE [dbo].[TestingTPS] (

	[Bahan] float NULL, 
	[UnitReturn] int NULL, 
	[Name] varchar(8000) NULL, 
	[AbsensiDate] datetime2(6) NULL, 
	[TanggalAbsensi] varchar(8000) NULL, 
	[kehadiran] int NULL, 
	[JT] int NULL, 
	[ResourceNumber] varchar(8000) NULL, 
	[Outlet] varchar(8000) NULL, 
	[Jabatan] varchar(8000) NULL, 
	[PartyNumber] varchar(8000) NULL, 
	[level] varchar(8000) NULL, 
	[DealerName] varchar(8000) NULL, 
	[DealerCode] varchar(8000) NULL, 
	[ProjId] varchar(8000) NULL, 
	[Act] float NULL, 
	[UnitServed] int NULL, 
	[Joblist] varchar(8000) NULL, 
	[GroupJobList] varchar(8000) NULL, 
	[Fr] float NULL, 
	[Jasa] float NULL, 
	[Part] float NULL, 
	[OutletName] varchar(8000) NULL, 
	[OutletNew] varchar(8000) NULL
);