CREATE TABLE [dbo].[WRKCTRTABLE] (

	[BottleneckResource] varchar(8000) NULL, 
	[Capacity] float NULL, 
	[CapacityBatch] float NULL, 
	[CapLimited] varchar(8000) NULL, 
	[CapUnit] varchar(8000) NULL, 
	[Created] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[EffectivityPct] float NULL, 
	[ErrorPct] float NULL, 
	[Exclusive] varchar(8000) NULL, 
	[IsIndividualResource] varchar(8000) NULL, 
	[Name] varchar(8000) NULL, 
	[OperationSchedPct] float NULL, 
	[PMFSequenceGroupId] varchar(8000) NULL, 
	[ProcessCategoryId] varchar(8000) NULL, 
	[ProcessPerQty] float NULL, 
	[ProcessTime] float NULL, 
	[PropertyLimited] varchar(8000) NULL, 
	[QtyCategoryId] varchar(8000) NULL, 
	[QueueTimeAfter] float NULL, 
	[QueueTimeBefore] float NULL, 
	[RecordId] bigint NULL, 
	[RouteGroupId] varchar(8000) NULL, 
	[SetUpCategoryId] varchar(8000) NULL, 
	[SetupTime] float NULL, 
	[ToHours] float NULL, 
	[TransferBatch] float NULL, 
	[TranspTime] float NULL, 
	[VendId] varchar(8000) NULL, 
	[Worker] bigint NULL, 
	[WrkCtrId] varchar(8000) NULL, 
	[WrkCtrType] varchar(8000) NULL
);