CREATE   Procedure SP_AUTOMAIL_VIN_EXPORT_DELETION AS

DELETE A FROM SILVER_WAREHOUSE.dbo.AUTOMAIL_VIN_EXPORT A join BRONZE_WAREHOUSE.dbo.AUTOMAIL_VIN_EXPORT B on A.IAMIInvNumber = B.IAMIInvNumber
and A.IAMIInvDate = B.IAMIInvDate and A.VIN =B.VIN  where B.Deletion is NOT Null

insert into SILVER_WAREHOUSE.dbo.AUTOMAIL_VIN_EXPORT
SELECT distinct * FROM BRONZE_WAREHOUSE.dbo.AUTOMAIL_VIN_EXPORT where Deletion is NOT null