CREATE PROCEDURE SP_INGEST_VENDTABLE
AS
BEGIN
    -- Step 1: Update existing records
    UPDATE target
    SET
       target.AddressBooks=        source.AddressBooks,
target.AddressBrazilianCNPJOrCPF=        source.AddressBrazilianCNPJOrCPF,
target.AddressBrazilianIE=        source.AddressBrazilianIE,
target.AddressBuildingCompliment=        source.AddressBuildingCompliment,
target.AddressCity=        source.AddressCity,
target.AddressCityInKana=        source.AddressCityInKana,
target.AddressCountryRegionId=        source.AddressCountryRegionId,
target.AddressCountryRegionISOCode=        source.AddressCountryRegionISOCode,
target.AddressCountyId=        source.AddressCountyId,
target.AddressDescription=        source.AddressDescription,
target.AddressDistrictName=        source.AddressDistrictName,
target.AddressLatitude=        source.AddressLatitude,
target.AddressLocationId=        source.AddressLocationId,
target.AddressLocationRoles=        source.AddressLocationRoles,
target.AddressLongitude=        source.AddressLongitude,
target.AddressPostBox=        source.AddressPostBox,
target.AddressStateId=        source.AddressStateId,
target.AddressStreet=        source.AddressStreet,
target.AddressStreetInKana=        source.AddressStreetInKana,
target.AddressStreetNumber=        source.AddressStreetNumber,
target.AddressTimeZone=        source.AddressTimeZone,
target.AddressValidFrom=        source.AddressValidFrom,
target.AddressValidTo=        source.AddressValidTo,
target.AddressZipCode=        source.AddressZipCode,
target.AgitUsePODuration=        source.AgitUsePODuration,
target.ArePricesIncludingSalesTax=        source.ArePricesIncludingSalesTax,
target.BankAccountId=        source.BankAccountId,
target.BankOrderOfPayment=        source.BankOrderOfPayment,
target.BankTransactionType=        source.BankTransactionType,
target.BirthCountyCode=        source.BirthCountyCode,
target.BirthPlace=        source.BirthPlace,
target.BrazilianCCM=        source.BrazilianCCM,
target.BrazilianCNAE=        source.BrazilianCNAE,
target.BrazilianCNPJOrCPF=        source.BrazilianCNPJOrCPF,
target.BrazilianIE=        source.BrazilianIE,
target.BrazilianINSSCEI=        source.BrazilianINSSCEI,
target.BrazilianNIT=        source.BrazilianNIT,
target.BusinessSegmentCode=        source.BusinessSegmentCode,
target.BusinessSubsegmentCode=        source.BusinessSubsegmentCode,
target.BuyerGroupId=        source.BuyerGroupId,
target.CashDiscountCode=        source.CashDiscountCode,
target.CentralBankPurposeCode=        source.CentralBankPurposeCode,
target.CentralBankPurposeText=        source.CentralBankPurposeText,
target.ChargeVendorGroupId=        source.ChargeVendorGroupId,
target.CISCompanyRegistrationNumber=        source.CISCompanyRegistrationNumber,
target.CISNationalInsuranceNumber=        source.CISNationalInsuranceNumber,
target.CISStatus=        source.CISStatus,
target.CISUniqueTaxPayerReference=        source.CISUniqueTaxPayerReference,
target.CISVerificationDate=        source.CISVerificationDate,
target.CISVerificationNumber=        source.CISVerificationNumber,
target.ClearingPeriodPaymentTermsId=        source.ClearingPeriodPaymentTermsId,
target.CommercialRegisterInsetNumber=        source.CommercialRegisterInsetNumber,
target.CommercialRegisterName=        source.CommercialRegisterName,
target.CommercialRegisterSection=        source.CommercialRegisterSection,
target.CompanyChainName=        source.CompanyChainName,
target.CompanyType=        source.CompanyType,
target.CompositionScheme=        source.CompositionScheme,
target.CreatedDateTime1=        source.CreatedDateTime1,
target.CreditLimit=        source.CreditLimit,
target.CreditRating=        source.CreditRating,
target.CurrencyCode=        source.CurrencyCode,
target.CUSIPDetails=        source.CUSIPDetails,
target.CUSIPIdentificationNumber=        source.CUSIPIdentificationNumber,
target.dataAreaId=        source.dataAreaId,
target.DefaultCashDiscountUsage=        source.DefaultCashDiscountUsage,
target.DefaultDeliveryModeId=        source.DefaultDeliveryModeId,
target.DefaultDeliveryTermsCode=        source.DefaultDeliveryTermsCode,
target.DefaultInventoryStatusId=        source.DefaultInventoryStatusId,
target.DefaultLedgerDimensionDisplayValue=        source.DefaultLedgerDimensionDisplayValue,
target.DefaultOffsetAccountType=        source.DefaultOffsetAccountType,
target.DefaultOffsetLedgerAccountDisplayValue=        source.DefaultOffsetLedgerAccountDisplayValue,
target.DefaultPaymentDayName=        source.DefaultPaymentDayName,
target.DefaultPaymentScheduleName=        source.DefaultPaymentScheduleName,
target.DefaultPaymentTermsName=        source.DefaultPaymentTermsName,
target.DefaultProcumentWarehouseId=        source.DefaultProcumentWarehouseId,
target.DefaultPurchaseOrderPoolId=        source.DefaultPurchaseOrderPoolId,
target.DefaultPurchaseSiteId=        source.DefaultPurchaseSiteId,
target.DefaultSupplementaryProductVendorGroupId=        source.DefaultSupplementaryProductVendorGroupId,
target.DefaultTotalDiscountVendorGroupCode=        source.DefaultTotalDiscountVendorGroupCode,
target.DefaultVendorPaymentMethodName=        source.DefaultVendorPaymentMethodName,
target.DestinationCode=        source.DestinationCode,
target.DIOTCountryCode=        source.DIOTCountryCode,
target.DIOTOperationType=        source.DIOTOperationType,
target.DIOTVendorType=        source.DIOTVendorType,
target.DUNSNumber=        source.DUNSNumber,
target.ElectronicLocationId=        source.ElectronicLocationId,
target.EnterpriseNumber=        source.EnterpriseNumber,
target.EthnicOriginId=        source.EthnicOriginId,
target.FactoringVendorAccountNumber=        source.FactoringVendorAccountNumber,
target.FiscalCode=        source.FiscalCode,
target.FiscalDocumentIncomeCode=        source.FiscalDocumentIncomeCode,
target.FiscalOperationPresenceType=        source.FiscalOperationPresenceType,
target.ForeignerId=        source.ForeignerId,
target.ForeignResident=        source.ForeignResident,
target.ForeignVendor=        source.ForeignVendor,
target.ForeignVendorTaxRegistrationId=        source.ForeignVendorTaxRegistrationId,
target.FormattedPrimaryAddress=        source.FormattedPrimaryAddress,
target.GTAVendor=        source.GTAVendor,
target.HasOnlyTakenBids=        source.HasOnlyTakenBids,
target.InventoryProfile=        source.InventoryProfile,
target.InventoryProfileType=        source.InventoryProfileType,
target.InvoiceVendorAccountNumber=        source.InvoiceVendorAccountNumber,
target.IsChangeManagementActivated=        source.IsChangeManagementActivated,
target.IsChangeMangementOverrideByVendorAllowed=        source.IsChangeMangementOverrideByVendorAllowed,
target.IsCUSIPIdentificationNumberApplicable=        source.IsCUSIPIdentificationNumberApplicable,
target.IsFlaggedWithSecondTIN=        source.IsFlaggedWithSecondTIN,
target.IsForeignEntity=        source.IsForeignEntity,
target.IsGSTCompositionSchemeEnabled=        source.IsGSTCompositionSchemeEnabled,
target.IsICMSContributor=        source.IsICMSContributor,
target.IsIncomingFiscalDocumentGenerated=        source.IsIncomingFiscalDocumentGenerated,
target.IsMinorityOwned=        source.IsMinorityOwned,
target.ISNationalRegistryNumber=        source.ISNationalRegistryNumber,
target.IsOneTimeVendor=        source.IsOneTimeVendor,
target.IsOwnerDisabled=        source.IsOwnerDisabled,
target.IsPrimaryEmailAddressIMEnabled=        source.IsPrimaryEmailAddressIMEnabled,
target.IsPrimaryPhoneNumberMobile=        source.IsPrimaryPhoneNumberMobile,
target.IsPurchaseConsumed=        source.IsPurchaseConsumed,
target.IsPurchaseOrderChangeRequestOverrideAllowed=        source.IsPurchaseOrderChangeRequestOverrideAllowed,
target.IsReportingTax1099=        source.IsReportingTax1099,
target.IsServiceDeliveryAddressBased=        source.IsServiceDeliveryAddressBased,
target.IsServiceVeteranOwned=        source.IsServiceVeteranOwned,
target.IsSmallBusiness=        source.IsSmallBusiness,
target.IsSubcontractor=        source.IsSubcontractor,
target.IsVendorLocallyOwned=        source.IsVendorLocallyOwned,
target.IsVendorLocatedInHUBZone=        source.IsVendorLocatedInHUBZone,
target.IsVendorPayingBankPaymentFee=        source.IsVendorPayingBankPaymentFee,
target.IsW9CheckingEnabled=        source.IsW9CheckingEnabled,
target.IsW9Received=        source.IsW9Received,
target.IsWithholdingTaxCalculated=        source.IsWithholdingTaxCalculated,
target.IsWomanOwner=        source.IsWomanOwner,
target.KREDigunggung=        source.KREDigunggung,
target.KREImport=        source.KREImport,
target.KRETaxPajakDibebaskanId=        source.KRETaxPajakDibebaskanId,
target.KRETaxPrefixNumber=        source.KRETaxPrefixNumber,
target.KRETaxPrefixNumberWAPU=        source.KRETaxPrefixNumberWAPU,
target.KREWAPU=        source.KREWAPU,
target.LanguageId=        source.LanguageId,
target.LineDiscountVendorGroupCode=        source.LineDiscountVendorGroupCode,
target.LineOfBusinessId=        source.LineOfBusinessId,
target.MainContactPersonnelNumber=        source.MainContactPersonnelNumber,
target.ModifiedDateTime1=        source.ModifiedDateTime1,
target.MultilineDiscountVendorGroupCode=        source.MultilineDiscountVendorGroupCode,
target.NAFCode=        source.NAFCode,
target.NameControl=        source.NameControl,
target.Nationality=        source.Nationality,
target.NationalRegistryNumberId=        source.NationalRegistryNumberId,
target.NatureOfAssessee=        source.NatureOfAssessee,
target.Notes=        source.Notes,
target.NumberSequenceGroupId=        source.NumberSequenceGroupId,
target.OIDInvestorType=        source.OIDInvestorType,
target.OIDNomineeDetails=        source.OIDNomineeDetails,
target.OnHoldStatus=        source.OnHoldStatus,
target.OrganizationABCCode=        source.OrganizationABCCode,
target.OrganizationEmployeeAmount=        source.OrganizationEmployeeAmount,
target.OrganizationNumber=        source.OrganizationNumber,
target.OrganizationPhoneticName=        source.OrganizationPhoneticName,
target.OurAccountNumber=        source.OurAccountNumber,
target.PANNumber=        source.PANNumber,
target.PANReferenceNumber=        source.PANReferenceNumber,
target.PANStatus=        source.PANStatus,
target.Party=        source.Party,
target.PaymentFeeGroupId=        source.PaymentFeeGroupId,
target.PaymentId=        source.PaymentId,
target.PaymentSpecificationId=        source.PaymentSpecificationId,
target.PaymentTransactionCode=        source.PaymentTransactionCode,
target.PersonAnniversaryDay=        source.PersonAnniversaryDay,
target.PersonAnniversaryMonth=        source.PersonAnniversaryMonth,
target.PersonAnniversaryYear=        source.PersonAnniversaryYear,
target.PersonBirthDay=        source.PersonBirthDay,
target.PersonBirthMonth=        source.PersonBirthMonth,
target.PersonBirthYear=        source.PersonBirthYear,
target.PersonChildrenNames=        source.PersonChildrenNames,
target.PersonFirstName=        source.PersonFirstName,
target.PersonGender=        source.PersonGender,
target.PersonHobbies=        source.PersonHobbies,
target.PersonInitials=        source.PersonInitials,
target.PersonLastName=        source.PersonLastName,
target.PersonLastNamePrefix=        source.PersonLastNamePrefix,
target.PersonMaritalStatus=        source.PersonMaritalStatus,
target.PersonMiddleName=        source.PersonMiddleName,
target.PersonPersonalSuffix=        source.PersonPersonalSuffix,
target.PersonPersonalTitle=        source.PersonPersonalTitle,
target.PersonPhoneticFirstName=        source.PersonPhoneticFirstName,
target.PersonPhoneticLastName=        source.PersonPhoneticLastName,
target.PersonPhoneticMiddleName=        source.PersonPhoneticMiddleName,
target.PersonProfessionalSuffix=        source.PersonProfessionalSuffix,
target.PersonProfessionalTitle=        source.PersonProfessionalTitle,
target.PreferentialVendor=        source.PreferentialVendor,
target.PriceVendorGroupId=        source.PriceVendorGroupId,
target.PrimaryContactPersonId=        source.PrimaryContactPersonId,
target.PrimaryEmailAddress=        source.PrimaryEmailAddress,
target.PrimaryEmailAddressDescription=        source.PrimaryEmailAddressDescription,
target.PrimaryEmailAddressPurpose=        source.PrimaryEmailAddressPurpose,
target.PrimaryFacebook=        source.PrimaryFacebook,
target.PrimaryFacebookDescription=        source.PrimaryFacebookDescription,
target.PrimaryFacebookPurpose=        source.PrimaryFacebookPurpose,
target.PrimaryFaxNumber=        source.PrimaryFaxNumber,
target.PrimaryFaxNumberDescription=        source.PrimaryFaxNumberDescription,
target.PrimaryFaxNumberExtension=        source.PrimaryFaxNumberExtension,
target.PrimaryFaxNumberPurpose=        source.PrimaryFaxNumberPurpose,
target.PrimaryLinkedIn=        source.PrimaryLinkedIn,
target.PrimaryLinkedInDescription=        source.PrimaryLinkedInDescription,
target.PrimaryLinkedInPurpose=        source.PrimaryLinkedInPurpose,
target.PrimaryPhoneNumber=        source.PrimaryPhoneNumber,
target.PrimaryPhoneNumberDescription=        source.PrimaryPhoneNumberDescription,
target.PrimaryPhoneNumberExtension=        source.PrimaryPhoneNumberExtension,
target.PrimaryPhoneNumberPurpose=        source.PrimaryPhoneNumberPurpose,
target.PrimaryTelex=        source.PrimaryTelex,
target.PrimaryTelexDescription=        source.PrimaryTelexDescription,
target.PrimaryTelexPurpose=        source.PrimaryTelexPurpose,
target.PrimaryTwitter=        source.PrimaryTwitter,
target.PrimaryTwitterDescription=        source.PrimaryTwitterDescription,
target.PrimaryTwitterPurpose=        source.PrimaryTwitterPurpose,
target.PrimaryURL=        source.PrimaryURL,
target.PrimaryURLDescription=        source.PrimaryURLDescription,
target.PrimaryURLPurpose=        source.PrimaryURLPurpose,
target.ProductDescriptionVendorGroupId=        source.ProductDescriptionVendorGroupId,
target.PurchaseOrderConsolidationDayOfMonth=        source.PurchaseOrderConsolidationDayOfMonth,
target.PurchaseRebateVendorGroupId=        source.PurchaseRebateVendorGroupId,
target.PurchaseWorkCalendarId=        source.PurchaseWorkCalendarId,
target.RecordId=        source.RecordId,
target.ResidenceForeignCountryRegionId=        source.ResidenceForeignCountryRegionId,
target.RFCFederalTaxNumber=        source.RFCFederalTaxNumber,
target.SalesTaxGroupCode=        source.SalesTaxGroupCode,
target.SeparateDivisionId=        source.SeparateDivisionId,
target.SiretNumber=        source.SiretNumber,
target.SSIValidityDate=        source.SSIValidityDate,
target.SSIVendor=        source.SSIVendor,
target.StateInscription=        source.StateInscription,
target.StructureDepartment=        source.StructureDepartment,
target.Tax1099BoxId=        source.Tax1099BoxId,
target.Tax1099DoingBusinessAsName=        source.Tax1099DoingBusinessAsName,
target.Tax1099FederalTaxId=        source.Tax1099FederalTaxId,
target.Tax1099IdType=        source.Tax1099IdType,
target.Tax1099NameToUse=        source.Tax1099NameToUse,
target.Tax1099Type=        source.Tax1099Type,
target.TaxAgent=        source.TaxAgent,
target.TaxExemptNumber=        source.TaxExemptNumber,
target.TaxOperationCode=        source.TaxOperationCode,
target.TaxPartnerKind=        source.TaxPartnerKind,
target.TCSGroup=        source.TCSGroup,
target.TDSGroup=        source.TDSGroup,
target.UniquePopulationRegistryCode=        source.UniquePopulationRegistryCode,
target.UPSFreightZone=        source.UPSFreightZone,
target.VendorAccountNumber=        source.VendorAccountNumber,
target.VendorExceptionGroupId=        source.VendorExceptionGroupId,
target.VendorGroupId=        source.VendorGroupId,
target.VendorHoldReleaseDate=        source.VendorHoldReleaseDate,
target.VendorInvoiceDeclarationId=        source.VendorInvoiceDeclarationId,
target.VendorInvoiceLineMatchingPolicy=        source.VendorInvoiceLineMatchingPolicy,
target.VendorKnownAsName=        source.VendorKnownAsName,
target.VendorOrganizationName=        source.VendorOrganizationName,
target.VendorPartyNumber=        source.VendorPartyNumber,
target.VendorPartyType=        source.VendorPartyType,
target.VendorPaymentFinancialInterestCode=        source.VendorPaymentFinancialInterestCode,
target.VendorPaymentFineCode=        source.VendorPaymentFineCode,
target.VendorPortalCollaborationMethod=        source.VendorPortalCollaborationMethod,
target.VendorPriceToleranceGroupId=        source.VendorPriceToleranceGroupId,
target.VendorSearchName=        source.VendorSearchName,
target.WillInvoiceProcessingSummaryUpdatePurchaseOrder=        source.WillInvoiceProcessingSummaryUpdatePurchaseOrder,
target.WillProductReceiptProcessingSummaryUpdatePurchaseOrder=        source.WillProductReceiptProcessingSummaryUpdatePurchaseOrder,
target.WillPurchaseOrderIncludePricesAndAmounts=        source.WillPurchaseOrderIncludePricesAndAmounts,
target.WillPurchaseOrderProcessingSummaryUpdatePurchaseOrder=        source.WillPurchaseOrderProcessingSummaryUpdatePurchaseOrder,
target.WillReceiptsListProcessingSummaryUpdatePurchaseOrder=        source.WillReceiptsListProcessingSummaryUpdatePurchaseOrder,
target.WithholdingTaxGroupCode=        source.WithholdingTaxGroupCode,
target.WithholdingTaxVendorType=        source.WithholdingTaxVendorType,
target.ZAfterVendConfirm=        source.ZAfterVendConfirm,
target.ZakatFileNumber=        source.ZakatFileNumber,
target.ZakatRegistrationNumber=        source.ZakatRegistrationNumber,
target.ZakatServiceType=        source.ZakatServiceType,
target.Last_update=        getdate()
    FROM SILVER_WAREHOUSE.dbo.VendTable AS target
    JOIN (
        SELECT DISTINCT *
        FROM BRONZE_LAKEHOUSE.dbo.temp_VendTable
    ) AS source
    ON source.RecordId = target.RecordId;

    -- Step 2: Insert new records
    INSERT INTO SILVER_WAREHOUSE.dbo.VendTable (
       AddressBooks,
AddressBrazilianCNPJOrCPF,
AddressBrazilianIE,
AddressBuildingCompliment,
AddressCity,
AddressCityInKana,
AddressCountryRegionId,
AddressCountryRegionISOCode,
AddressCountyId,
AddressDescription,
AddressDistrictName,
AddressLatitude,
AddressLocationId,
AddressLocationRoles,
AddressLongitude,
AddressPostBox,
AddressStateId,
AddressStreet,
AddressStreetInKana,
AddressStreetNumber,
AddressTimeZone,
AddressValidFrom,
AddressValidTo,
AddressZipCode,
AgitUsePODuration,
ArePricesIncludingSalesTax,
BankAccountId,
BankOrderOfPayment,
BankTransactionType,
BirthCountyCode,
BirthPlace,
BrazilianCCM,
BrazilianCNAE,
BrazilianCNPJOrCPF,
BrazilianIE,
BrazilianINSSCEI,
BrazilianNIT,
BusinessSegmentCode,
BusinessSubsegmentCode,
BuyerGroupId,
CashDiscountCode,
CentralBankPurposeCode,
CentralBankPurposeText,
ChargeVendorGroupId,
CISCompanyRegistrationNumber,
CISNationalInsuranceNumber,
CISStatus,
CISUniqueTaxPayerReference,
CISVerificationDate,
CISVerificationNumber,
ClearingPeriodPaymentTermsId,
CommercialRegisterInsetNumber,
CommercialRegisterName,
CommercialRegisterSection,
CompanyChainName,
CompanyType,
CompositionScheme,
CreatedDateTime1,
CreditLimit,
CreditRating,
CurrencyCode,
CUSIPDetails,
CUSIPIdentificationNumber,
dataAreaId,
DefaultCashDiscountUsage,
DefaultDeliveryModeId,
DefaultDeliveryTermsCode,
DefaultInventoryStatusId,
DefaultLedgerDimensionDisplayValue,
DefaultOffsetAccountType,
DefaultOffsetLedgerAccountDisplayValue,
DefaultPaymentDayName,
DefaultPaymentScheduleName,
DefaultPaymentTermsName,
DefaultProcumentWarehouseId,
DefaultPurchaseOrderPoolId,
DefaultPurchaseSiteId,
DefaultSupplementaryProductVendorGroupId,
DefaultTotalDiscountVendorGroupCode,
DefaultVendorPaymentMethodName,
DestinationCode,
DIOTCountryCode,
DIOTOperationType,
DIOTVendorType,
DUNSNumber,
ElectronicLocationId,
EnterpriseNumber,
EthnicOriginId,
FactoringVendorAccountNumber,
FiscalCode,
FiscalDocumentIncomeCode,
FiscalOperationPresenceType,
ForeignerId,
ForeignResident,
ForeignVendor,
ForeignVendorTaxRegistrationId,
FormattedPrimaryAddress,
GTAVendor,
HasOnlyTakenBids,
InventoryProfile,
InventoryProfileType,
InvoiceVendorAccountNumber,
IsChangeManagementActivated,
IsChangeMangementOverrideByVendorAllowed,
IsCUSIPIdentificationNumberApplicable,
IsFlaggedWithSecondTIN,
IsForeignEntity,
IsGSTCompositionSchemeEnabled,
IsICMSContributor,
IsIncomingFiscalDocumentGenerated,
IsMinorityOwned,
ISNationalRegistryNumber,
IsOneTimeVendor,
IsOwnerDisabled,
IsPrimaryEmailAddressIMEnabled,
IsPrimaryPhoneNumberMobile,
IsPurchaseConsumed,
IsPurchaseOrderChangeRequestOverrideAllowed,
IsReportingTax1099,
IsServiceDeliveryAddressBased,
IsServiceVeteranOwned,
IsSmallBusiness,
IsSubcontractor,
IsVendorLocallyOwned,
IsVendorLocatedInHUBZone,
IsVendorPayingBankPaymentFee,
IsW9CheckingEnabled,
IsW9Received,
IsWithholdingTaxCalculated,
IsWomanOwner,
KREDigunggung,
KREImport,
KRETaxPajakDibebaskanId,
KRETaxPrefixNumber,
KRETaxPrefixNumberWAPU,
KREWAPU,
LanguageId,
LineDiscountVendorGroupCode,
LineOfBusinessId,
MainContactPersonnelNumber,
ModifiedDateTime1,
MultilineDiscountVendorGroupCode,
NAFCode,
NameControl,
Nationality,
NationalRegistryNumberId,
NatureOfAssessee,
Notes,
NumberSequenceGroupId,
OIDInvestorType,
OIDNomineeDetails,
OnHoldStatus,
OrganizationABCCode,
OrganizationEmployeeAmount,
OrganizationNumber,
OrganizationPhoneticName,
OurAccountNumber,
PANNumber,
PANReferenceNumber,
PANStatus,
Party,
PaymentFeeGroupId,
PaymentId,
PaymentSpecificationId,
PaymentTransactionCode,
PersonAnniversaryDay,
PersonAnniversaryMonth,
PersonAnniversaryYear,
PersonBirthDay,
PersonBirthMonth,
PersonBirthYear,
PersonChildrenNames,
PersonFirstName,
PersonGender,
PersonHobbies,
PersonInitials,
PersonLastName,
PersonLastNamePrefix,
PersonMaritalStatus,
PersonMiddleName,
PersonPersonalSuffix,
PersonPersonalTitle,
PersonPhoneticFirstName,
PersonPhoneticLastName,
PersonPhoneticMiddleName,
PersonProfessionalSuffix,
PersonProfessionalTitle,
PreferentialVendor,
PriceVendorGroupId,
PrimaryContactPersonId,
PrimaryEmailAddress,
PrimaryEmailAddressDescription,
PrimaryEmailAddressPurpose,
PrimaryFacebook,
PrimaryFacebookDescription,
PrimaryFacebookPurpose,
PrimaryFaxNumber,
PrimaryFaxNumberDescription,
PrimaryFaxNumberExtension,
PrimaryFaxNumberPurpose,
PrimaryLinkedIn,
PrimaryLinkedInDescription,
PrimaryLinkedInPurpose,
PrimaryPhoneNumber,
PrimaryPhoneNumberDescription,
PrimaryPhoneNumberExtension,
PrimaryPhoneNumberPurpose,
PrimaryTelex,
PrimaryTelexDescription,
PrimaryTelexPurpose,
PrimaryTwitter,
PrimaryTwitterDescription,
PrimaryTwitterPurpose,
PrimaryURL,
PrimaryURLDescription,
PrimaryURLPurpose,
ProductDescriptionVendorGroupId,
PurchaseOrderConsolidationDayOfMonth,
PurchaseRebateVendorGroupId,
PurchaseWorkCalendarId,
RecordId,
ResidenceForeignCountryRegionId,
RFCFederalTaxNumber,
SalesTaxGroupCode,
SeparateDivisionId,
SiretNumber,
SSIValidityDate,
SSIVendor,
StateInscription,
StructureDepartment,
Tax1099BoxId,
Tax1099DoingBusinessAsName,
Tax1099FederalTaxId,
Tax1099IdType,
Tax1099NameToUse,
Tax1099Type,
TaxAgent,
TaxExemptNumber,
TaxOperationCode,
TaxPartnerKind,
TCSGroup,
TDSGroup,
UniquePopulationRegistryCode,
UPSFreightZone,
VendorAccountNumber,
VendorExceptionGroupId,
VendorGroupId,
VendorHoldReleaseDate,
VendorInvoiceDeclarationId,
VendorInvoiceLineMatchingPolicy,
VendorKnownAsName,
VendorOrganizationName,
VendorPartyNumber,
VendorPartyType,
VendorPaymentFinancialInterestCode,
VendorPaymentFineCode,
VendorPortalCollaborationMethod,
VendorPriceToleranceGroupId,
VendorSearchName,
WillInvoiceProcessingSummaryUpdatePurchaseOrder,
WillProductReceiptProcessingSummaryUpdatePurchaseOrder,
WillPurchaseOrderIncludePricesAndAmounts,
WillPurchaseOrderProcessingSummaryUpdatePurchaseOrder,
WillReceiptsListProcessingSummaryUpdatePurchaseOrder,
WithholdingTaxGroupCode,
WithholdingTaxVendorType,
ZAfterVendConfirm,
ZakatFileNumber,
ZakatRegistrationNumber,
ZakatServiceType,
Last_update
    )
    SELECT
       source.AddressBooks,
source.AddressBrazilianCNPJOrCPF,
source.AddressBrazilianIE,
source.AddressBuildingCompliment,
source.AddressCity,
source.AddressCityInKana,
source.AddressCountryRegionId,
source.AddressCountryRegionISOCode,
source.AddressCountyId,
source.AddressDescription,
source.AddressDistrictName,
source.AddressLatitude,
source.AddressLocationId,
source.AddressLocationRoles,
source.AddressLongitude,
source.AddressPostBox,
source.AddressStateId,
source.AddressStreet,
source.AddressStreetInKana,
source.AddressStreetNumber,
source.AddressTimeZone,
source.AddressValidFrom,
source.AddressValidTo,
source.AddressZipCode,
source.AgitUsePODuration,
source.ArePricesIncludingSalesTax,
source.BankAccountId,
source.BankOrderOfPayment,
source.BankTransactionType,
source.BirthCountyCode,
source.BirthPlace,
source.BrazilianCCM,
source.BrazilianCNAE,
source.BrazilianCNPJOrCPF,
source.BrazilianIE,
source.BrazilianINSSCEI,
source.BrazilianNIT,
source.BusinessSegmentCode,
source.BusinessSubsegmentCode,
source.BuyerGroupId,
source.CashDiscountCode,
source.CentralBankPurposeCode,
source.CentralBankPurposeText,
source.ChargeVendorGroupId,
source.CISCompanyRegistrationNumber,
source.CISNationalInsuranceNumber,
source.CISStatus,
source.CISUniqueTaxPayerReference,
source.CISVerificationDate,
source.CISVerificationNumber,
source.ClearingPeriodPaymentTermsId,
source.CommercialRegisterInsetNumber,
source.CommercialRegisterName,
source.CommercialRegisterSection,
source.CompanyChainName,
source.CompanyType,
source.CompositionScheme,
source.CreatedDateTime1,
source.CreditLimit,
source.CreditRating,
source.CurrencyCode,
source.CUSIPDetails,
source.CUSIPIdentificationNumber,
source.dataAreaId,
source.DefaultCashDiscountUsage,
source.DefaultDeliveryModeId,
source.DefaultDeliveryTermsCode,
source.DefaultInventoryStatusId,
source.DefaultLedgerDimensionDisplayValue,
source.DefaultOffsetAccountType,
source.DefaultOffsetLedgerAccountDisplayValue,
source.DefaultPaymentDayName,
source.DefaultPaymentScheduleName,
source.DefaultPaymentTermsName,
source.DefaultProcumentWarehouseId,
source.DefaultPurchaseOrderPoolId,
source.DefaultPurchaseSiteId,
source.DefaultSupplementaryProductVendorGroupId,
source.DefaultTotalDiscountVendorGroupCode,
source.DefaultVendorPaymentMethodName,
source.DestinationCode,
source.DIOTCountryCode,
source.DIOTOperationType,
source.DIOTVendorType,
source.DUNSNumber,
source.ElectronicLocationId,
source.EnterpriseNumber,
source.EthnicOriginId,
source.FactoringVendorAccountNumber,
source.FiscalCode,
source.FiscalDocumentIncomeCode,
source.FiscalOperationPresenceType,
source.ForeignerId,
source.ForeignResident,
source.ForeignVendor,
source.ForeignVendorTaxRegistrationId,
source.FormattedPrimaryAddress,
source.GTAVendor,
source.HasOnlyTakenBids,
source.InventoryProfile,
source.InventoryProfileType,
source.InvoiceVendorAccountNumber,
source.IsChangeManagementActivated,
source.IsChangeMangementOverrideByVendorAllowed,
source.IsCUSIPIdentificationNumberApplicable,
source.IsFlaggedWithSecondTIN,
source.IsForeignEntity,
source.IsGSTCompositionSchemeEnabled,
source.IsICMSContributor,
source.IsIncomingFiscalDocumentGenerated,
source.IsMinorityOwned,
source.ISNationalRegistryNumber,
source.IsOneTimeVendor,
source.IsOwnerDisabled,
source.IsPrimaryEmailAddressIMEnabled,
source.IsPrimaryPhoneNumberMobile,
source.IsPurchaseConsumed,
source.IsPurchaseOrderChangeRequestOverrideAllowed,
source.IsReportingTax1099,
source.IsServiceDeliveryAddressBased,
source.IsServiceVeteranOwned,
source.IsSmallBusiness,
source.IsSubcontractor,
source.IsVendorLocallyOwned,
source.IsVendorLocatedInHUBZone,
source.IsVendorPayingBankPaymentFee,
source.IsW9CheckingEnabled,
source.IsW9Received,
source.IsWithholdingTaxCalculated,
source.IsWomanOwner,
source.KREDigunggung,
source.KREImport,
source.KRETaxPajakDibebaskanId,
source.KRETaxPrefixNumber,
source.KRETaxPrefixNumberWAPU,
source.KREWAPU,
source.LanguageId,
source.LineDiscountVendorGroupCode,
source.LineOfBusinessId,
source.MainContactPersonnelNumber,
source.ModifiedDateTime1,
source.MultilineDiscountVendorGroupCode,
source.NAFCode,
source.NameControl,
source.Nationality,
source.NationalRegistryNumberId,
source.NatureOfAssessee,
source.Notes,
source.NumberSequenceGroupId,
source.OIDInvestorType,
source.OIDNomineeDetails,
source.OnHoldStatus,
source.OrganizationABCCode,
source.OrganizationEmployeeAmount,
source.OrganizationNumber,
source.OrganizationPhoneticName,
source.OurAccountNumber,
source.PANNumber,
source.PANReferenceNumber,
source.PANStatus,
source.Party,
source.PaymentFeeGroupId,
source.PaymentId,
source.PaymentSpecificationId,
source.PaymentTransactionCode,
source.PersonAnniversaryDay,
source.PersonAnniversaryMonth,
source.PersonAnniversaryYear,
source.PersonBirthDay,
source.PersonBirthMonth,
source.PersonBirthYear,
source.PersonChildrenNames,
source.PersonFirstName,
source.PersonGender,
source.PersonHobbies,
source.PersonInitials,
source.PersonLastName,
source.PersonLastNamePrefix,
source.PersonMaritalStatus,
source.PersonMiddleName,
source.PersonPersonalSuffix,
source.PersonPersonalTitle,
source.PersonPhoneticFirstName,
source.PersonPhoneticLastName,
source.PersonPhoneticMiddleName,
source.PersonProfessionalSuffix,
source.PersonProfessionalTitle,
source.PreferentialVendor,
source.PriceVendorGroupId,
source.PrimaryContactPersonId,
source.PrimaryEmailAddress,
source.PrimaryEmailAddressDescription,
source.PrimaryEmailAddressPurpose,
source.PrimaryFacebook,
source.PrimaryFacebookDescription,
source.PrimaryFacebookPurpose,
source.PrimaryFaxNumber,
source.PrimaryFaxNumberDescription,
source.PrimaryFaxNumberExtension,
source.PrimaryFaxNumberPurpose,
source.PrimaryLinkedIn,
source.PrimaryLinkedInDescription,
source.PrimaryLinkedInPurpose,
source.PrimaryPhoneNumber,
source.PrimaryPhoneNumberDescription,
source.PrimaryPhoneNumberExtension,
source.PrimaryPhoneNumberPurpose,
source.PrimaryTelex,
source.PrimaryTelexDescription,
source.PrimaryTelexPurpose,
source.PrimaryTwitter,
source.PrimaryTwitterDescription,
source.PrimaryTwitterPurpose,
source.PrimaryURL,
source.PrimaryURLDescription,
source.PrimaryURLPurpose,
source.ProductDescriptionVendorGroupId,
source.PurchaseOrderConsolidationDayOfMonth,
source.PurchaseRebateVendorGroupId,
source.PurchaseWorkCalendarId,
source.RecordId,
source.ResidenceForeignCountryRegionId,
source.RFCFederalTaxNumber,
source.SalesTaxGroupCode,
source.SeparateDivisionId,
source.SiretNumber,
source.SSIValidityDate,
source.SSIVendor,
source.StateInscription,
source.StructureDepartment,
source.Tax1099BoxId,
source.Tax1099DoingBusinessAsName,
source.Tax1099FederalTaxId,
source.Tax1099IdType,
source.Tax1099NameToUse,
source.Tax1099Type,
source.TaxAgent,
source.TaxExemptNumber,
source.TaxOperationCode,
source.TaxPartnerKind,
source.TCSGroup,
source.TDSGroup,
source.UniquePopulationRegistryCode,
source.UPSFreightZone,
source.VendorAccountNumber,
source.VendorExceptionGroupId,
source.VendorGroupId,
source.VendorHoldReleaseDate,
source.VendorInvoiceDeclarationId,
source.VendorInvoiceLineMatchingPolicy,
source.VendorKnownAsName,
source.VendorOrganizationName,
source.VendorPartyNumber,
source.VendorPartyType,
source.VendorPaymentFinancialInterestCode,
source.VendorPaymentFineCode,
source.VendorPortalCollaborationMethod,
source.VendorPriceToleranceGroupId,
source.VendorSearchName,
source.WillInvoiceProcessingSummaryUpdatePurchaseOrder,
source.WillProductReceiptProcessingSummaryUpdatePurchaseOrder,
source.WillPurchaseOrderIncludePricesAndAmounts,
source.WillPurchaseOrderProcessingSummaryUpdatePurchaseOrder,
source.WillReceiptsListProcessingSummaryUpdatePurchaseOrder,
source.WithholdingTaxGroupCode,
source.WithholdingTaxVendorType,
source.ZAfterVendConfirm,
source.ZakatFileNumber,
source.ZakatRegistrationNumber,
source.ZakatServiceType,
getdate()
    FROM (
        SELECT DISTINCT *
        FROM BRONZE_LAKEHOUSE.dbo.temp_VendTable
    ) AS source
    LEFT JOIN SILVER_WAREHOUSE.dbo.VendTable AS target
       on source.RecordId = target.RecordId
  

   
END;