CREATE PROCEDURE SP_INGEST_ZGOODISSUESTNK AS
DELETE FROM SILVER_WAREHOUSE.dbo.ZGoodIssueSTNK
 WHERE PengajuanNoFakpol  IN (SELECT PengajuanNoFakpol FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodIssueSTNK GROUP BY PengajuanNoFakpol )


INSERT INTO SILVER_WAREHOUSE.dbo.ZGoodIssueSTNK
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodIssueSTNK