CREATE PROCEDURE SP_INGEST_WRKCTRTABLE as
delete from SILVER_WAREHOUSE.dbo.WRKCTRTABLE
insert into SILVER_WAREHOUSE.dbo.WRKCTRTABLE
select * from BRONZE_LAKEHOUSE.dbo.WRKCTRTABLE

--SELECT * INTO SILVER_WAREHOUSE.dbo.WRKCTRTABLE  from BRONZE_LAKEHOUSE.dbo.WRKCTRTABLE