CREATE PROCEDURE SP_INGEST_ZEFAKPOL AS

DELETE FROM SILVER_WAREHOUSE.dbo.ZEFakpol WHERE PengajuanFakpolNo IN (SELECT PengajuanFakpolNo FROM BRONZE_LAKEHOUSE.dbo.temp_ZEFakpol GROUP BY PengajuanFakpolNo)

INSERT INTO SILVER_WAREHOUSE.dbo.ZEFakpol
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZEFakpol where Site <>  ''