CREATE procedure SP_INGEST_INVENTITEMGROUPITEM AS
DELETE FROM SILVER_WAREHOUSE.dbo.InventItemGroupItem
 WHERE RecordId  IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_InventItemGroupItem)


INSERT INTO SILVER_WAREHOUSE.dbo.InventItemGroupItem
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_InventItemGroupItem