CREATE     PROCEDURE SP_INGEST_SITE_MAPPINGMERGEROUTLETSIS AS
DROP TABLE SILVER_WAREHOUSE.dbo.site_mappingMergerOutletSIS

SELECT * INTO site_mappingMergerOutletSIS
FROM (SELECT * FROM BRONZE_LAKEHOUSE_PSS.dbo.site_mappingMergerOutletSIS) a