CREATE   PROCEDURE SP_INGEST_SALES_OPPORTUNITY AS
DROP TABLE SILVER_WAREHOUSE.dbo.sales_Opportunity

SELECT * INTO sales_Opportunity
FROM (SELECT * FROM BRONZE_LAKEHOUSE_PSS.dbo.sales_Opportunity) a