CREATE   PROCEDURE SP_INGEST_SPAREPART_PURCHASEORDERPART AS
TRUNCATE TABLE SILVER_WAREHOUSE.dbo.Sparepart_purchaseOrderPart
insert into SILVER_WAREHOUSE.dbo.Sparepart_purchaseOrderPart
select * from BRONZE_LAKEHOUSE_PSS.dbo.Sparepart_purchaseOrderPart