CREATE procedure SP_INGEST_DIM AS
DELETE FROM SILVER_WAREHOUSE.dbo.Dim
 WHERE RecordId  IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_Dim)

INSERT INTO SILVER_WAREHOUSE.dbo.Dim
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_Dim Order by ModifiedDate