CREATE   PROCEDURE SP_INGEST_SALES_INVOICEPOUNIT AS
DROP TABLE SILVER_WAREHOUSE.dbo.sales_InvoicePOUnit

SELECT * INTO sales_InvoicePOUnit
FROM (SELECT * FROM BRONZE_LAKEHOUSE_PSS.dbo.sales_InvoicePOUnit) a