CREATE procedure SP_INGEST_ZEMPLOYMENT AS
DELETE FROM SILVER_WAREHOUSE.dbo.ZEmployment
 WHERE RecId1  IN (SELECT RecId1 FROM BRONZE_LAKEHOUSE.dbo.temp_ZEmployment )

INSERT INTO SILVER_WAREHOUSE.dbo.ZEmployment
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZEmployment Order by ModifiedDateTime1