CREATE     PROCEDURE SP_INGEST_SALES_TRANSFERORDER AS
DROP TABLE SILVER_WAREHOUSE.dbo.sales_TransferOrder

SELECT * INTO sales_TransferOrder
FROM (SELECT * FROM BRONZE_LAKEHOUSE_PSS.dbo.sales_TransferOrder) a