CREATE PROCEDURE SP_INGEST_ZGOODISSUEBPKB AS
DELETE FROM SILVER_WAREHOUSE.dbo.ZGoodIssueBPKB
 WHERE PengajuanFakpolNo  IN (SELECT PengajuanFakpolNo FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodIssueBPKB GROUP BY PengajuanFakpolNo )


INSERT INTO SILVER_WAREHOUSE.dbo.ZGoodIssueBPKB
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodIssueBPKB