CREATE   PROCEDURE SP_INGEST_ZCUSTOMERS AS
DELETE a
FROM SILVER_WAREHOUSE.dbo.ZCustomers a
INNER JOIN BRONZE_LAKEHOUSE.dbo.temp_ZCustomers b ON LOWER(b.AccountNum) = LOWER(a.AccountNum) AND LOWER(b.dataAreaId) = LOWER(a.dataAreaId)


INSERT INTO SILVER_WAREHOUSE.dbo.ZCustomers
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZCustomers