CREATE PROCEDURE SP_INGEST_AMINVENTDEMANDTRANS AS

DELETE FROM SILVER_WAREHOUSE.dbo.AMInventDemandTrans 
WHERE RecordId  IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_AMInventDemandTrans)

INSERT INTO SILVER_WAREHOUSE.dbo.AMInventDemandTrans 
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_AMInventDemandTrans Order by ModifiedDateTime1