CREATE PROCEDURE SP_INGEST_ZGOODRECEIPTSTNK AS

DELETE FROM SILVER_WAREHOUSE.dbo.ZGoodReceiptSTNK  
    WHERE PengajuanFakpolNo IN 
(SELECT PengajuanFakpolNo  FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodReceiptSTNK GROUP BY PengajuanFakpolNo )

INSERT INTO SILVER_WAREHOUSE.dbo.ZGoodReceiptSTNK
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodReceiptSTNK