CREATE PROCEDURE SP_INGEST_ZINVENTTABLES AS

DELETE FROM SILVER_WAREHOUSE.dbo.ZInventTables
 WHERE RecordId  IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_ZInventTables)

INSERT INTO SILVER_WAREHOUSE.dbo.ZInventTables
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZInventTables Order by ModifiedDateTime1