CREATE PROCEDURE SP_INGEST_ZGOODRECEIPTBPKB AS
DELETE FROM SILVER_WAREHOUSE.dbo.ZGoodReceiptBPKB
 WHERE PengajuanFakpolNo  IN (SELECT PengajuanFakpolNo FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodReceiptBPKB GROUP BY PengajuanFakpolNo )


INSERT INTO SILVER_WAREHOUSE.dbo.ZGoodReceiptBPKB
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZGoodReceiptBPKB