CREATE PROCEDURE SP_INGEST_ZINQABSENSIMEKANIKLINE AS

DELETE FROM SILVER_WAREHOUSE.dbo.ZInqAbsensiMekanikLine
WHERE RecordId IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_ZInqAbsensiMekanikLine)

INSERT INTO SILVER_WAREHOUSE.dbo.ZInqAbsensiMekanikLine
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_ZInqAbsensiMekanikLine Order by ModifiedDateTime