CREATE PROCEDURE SP_INGEST_SMMBUSRELTABLE AS

DELETE FROM SILVER_WAREHOUSE.dbo.smmBusRelTable
WHERE RecordId  IN (SELECT RecordId FROM BRONZE_LAKEHOUSE.dbo.temp_smmBusRelTable)

INSERT INTO SILVER_WAREHOUSE.dbo.smmBusRelTable
SELECT * FROM BRONZE_LAKEHOUSE.dbo.temp_smmBusRelTable order by ModifiedDateTime1