CREATE TABLE [dbo].[sales_Opportunity] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_opportunityNo] varchar(8000) NULL, 
	[data_createdDate] varchar(8000) NULL, 
	[data_namaProspect] varchar(8000) NULL, 
	[data_prospectNo] varchar(8000) NULL, 
	[data_statusProspect] varchar(8000) NULL, 
	[data_decisionMaker] varchar(8000) NULL, 
	[data_companyName] varchar(8000) NULL, 
	[data_department] varchar(8000) NULL, 
	[data_namaDealer] varchar(8000) NULL, 
	[data_kodeOutlet] varchar(8000) NULL, 
	[data_namaOutlet] varchar(8000) NULL, 
	[data_segmentation] varchar(8000) NULL, 
	[data_goodType] varchar(8000) NULL, 
	[data_beratYangDiangkut] bigint NULL, 
	[data_npkSalesman] varchar(8000) NULL, 
	[data_salesman] varchar(8000) NULL, 
	[data_npkSupervisor] varchar(8000) NULL, 
	[data_supervisor] varchar(8000) NULL, 
	[data_paymentType] varchar(8000) NULL, 
	[data_leasing] varchar(8000) NULL, 
	[data_address] varchar(8000) NULL, 
	[data_phone] varchar(8000) NULL, 
	[data_itemNo] varchar(8000) NULL, 
	[data_itemDesc] varchar(8000) NULL, 
	[data_color] varchar(8000) NULL, 
	[data_qtyUnit] bigint NULL, 
	[data_platType] varchar(8000) NULL, 
	[data_karoseriType] varchar(8000) NULL, 
	[data_customerType] varchar(8000) NULL
);