CREATE TABLE [dbo].[sales_invoiceSO] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_referenceNo] varchar(8000) NULL, 
	[data_referenceType] varchar(8000) NULL, 
	[data_invoiceNo] varchar(8000) NULL, 
	[data_invoiceDate] varchar(8000) NULL, 
	[data_invoiceStatus] varchar(8000) NULL, 
	[data_hargaJual] bigint NULL, 
	[data_itemUnitNo] varchar(8000) NULL, 
	[data_itemUnitDesc] varchar(8000) NULL, 
	[data_qtyUnit] bigint NULL, 
	[data_unitUnitPrice] bigint NULL, 
	[data_karoseries_itemKaroseriNo] varchar(8000) NULL, 
	[data_karoseries_itemKaroseriDesc] varchar(8000) NULL, 
	[data_karoseries_qtyKaroseri] bigint NULL, 
	[data_karoseries_unitKaroseriPrice] bigint NULL, 
	[data_accessories_itemAksesorisNo] varchar(8000) NULL, 
	[data_accessories_itemAksesorisDesc] varchar(8000) NULL, 
	[data_accessories_qtyAksesoris] bigint NULL, 
	[data_accessories_unitAksesorisPrice] bigint NULL, 
	[data_itemBBNNoticeNo] varchar(8000) NULL, 
	[data_itemBBNNoticeDesc] varchar(8000) NULL, 
	[data_unitBBNNoticePrice] bigint NULL, 
	[data_itemBiayaUbahBentukNo] varchar(8000) NULL, 
	[data_itemBiayaUbahBentukDesc] varchar(8000) NULL, 
	[data_unitBiayaUbahBentukPrice] bigint NULL, 
	[data_itemDiskonBBNNo] varchar(8000) NULL, 
	[data_itemDiskonBBNDesc] varchar(8000) NULL, 
	[data_unitDiskonBBNPrice] bigint NULL, 
	[data_accessories] varchar(8000) NULL, 
	[data_karoseries] varchar(8000) NULL, 
	[data_giDate] varchar(8000) NULL
);