CREATE TABLE [dbo].[service_invoiceWO] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_invoiceNo] varchar(8000) NULL, 
	[data_workOrderNo] varchar(8000) NULL, 
	[data_invoiceAccount] varchar(8000) NULL, 
	[data_invoiceName] varchar(8000) NULL, 
	[data_invoiceDate] varchar(8000) NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_operations_operationNo] varchar(8000) NULL, 
	[data_operations_operationDesc] varchar(8000) NULL, 
	[data_operations_hour] float NULL, 
	[data_parts_partNo] varchar(8000) NULL, 
	[data_parts_partDesc] varchar(8000) NULL, 
	[data_parts_qty] bigint NULL, 
	[data_parts_uOM] varchar(8000) NULL, 
	[data_consumables_consumableNo] varchar(8000) NULL, 
	[data_consumables_consumableDesc] varchar(8000) NULL, 
	[data_consumables_qty] bigint NULL, 
	[data_consumables_uOM] varchar(8000) NULL, 
	[data_parts] varchar(8000) NULL, 
	[data_consumables] varchar(8000) NULL, 
	[data_operations] varchar(8000) NULL, 
	[data_consumables_consumableItemNo] varchar(8000) NULL, 
	[data_parts_partItemNo] varchar(8000) NULL
);