CREATE TABLE [dbo].[AUTOMAIL_SPFUAI6_WILAYAH_DEV] (

	[BU] varchar(8000) NULL, 
	[MinorGroup] varchar(8000) NULL, 
	[Series] varchar(8000) NULL, 
	[NationalDOS] decimal(18,2) NULL, 
	[NationalAI] decimal(18,2) NULL, 
	[NationalTOT] decimal(18,2) NULL, 
	[SumbagutDOS] decimal(18,2) NULL, 
	[SumbagutAI] decimal(18,2) NULL, 
	[SumbagutTOT] decimal(18,2) NULL, 
	[SumbagselDOS] decimal(18,2) NULL, 
	[SumbagselAI] decimal(18,2) NULL, 
	[SumbagselTOT] decimal(18,2) NULL, 
	[JKTDOS] decimal(18,2) NULL, 
	[JKTAI] decimal(18,2) NULL, 
	[JKTTOT] decimal(18,2) NULL, 
	[JabarDOS] decimal(18,2) NULL, 
	[JabarAI] decimal(18,2) NULL, 
	[JabarTOT] decimal(18,2) NULL, 
	[JatengDOS] decimal(18,2) NULL, 
	[JatengAI] decimal(18,2) NULL, 
	[JatengTOT] decimal(18,2) NULL, 
	[JatimDOS] decimal(18,2) NULL, 
	[JatimAI] decimal(18,2) NULL, 
	[JatimTOT] decimal(18,2) NULL, 
	[KalimantanDOS] decimal(18,2) NULL, 
	[KalimantanAI] decimal(18,2) NULL, 
	[KalimantanTOT] decimal(18,2) NULL, 
	[Sul_IBTDOS] decimal(18,2) NULL, 
	[Sul_IBTAI] decimal(18,2) NULL, 
	[Sul_IBTTOT] decimal(18,2) NULL, 
	[PeriodFrom] varchar(8000) NULL, 
	[PeriodTo] varchar(8000) NULL, 
	[Last_Update] varchar(8000) NULL
);