CREATE TABLE [dbo].[sales_POKarAkse] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_kodeOutlet] varchar(8000) NULL, 
	[data_vendorNo] varchar(8000) NULL, 
	[data_vendorName] varchar(8000) NULL, 
	[data_poNo] varchar(8000) NULL, 
	[data_poStatus] varchar(8000) NULL, 
	[data_purchaseOrderType] varchar(8000) NULL, 
	[data_deliveryDate] varchar(8000) NULL, 
	[data_materials_itemNo] varchar(8000) NULL, 
	[data_materials_itemDesc] varchar(8000) NULL, 
	[data_materials_poQty] bigint NULL, 
	[data_materials_unitPrice] bigint NULL, 
	[data_serialNo] varchar(8000) NULL, 
	[data_warehouse] varchar(8000) NULL, 
	[data_invoiceNo] varchar(8000) NULL, 
	[data_invoiceDate] varchar(8000) NULL, 
	[data_materials] varchar(8000) NULL, 
	[data_materials_invoiceQty] bigint NULL, 
	[data_materials_invoiceAmount] bigint NULL, 
	[data_referenceNo] varchar(8000) NULL, 
	[data_referenceType] varchar(8000) NULL
);