CREATE TABLE [dbo].[sales_TransferOrder] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_okkNo] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_transferNo] varchar(8000) NULL, 
	[data_transferStatus] varchar(8000) NULL, 
	[data_transferType] varchar(8000) NULL, 
	[data_itemNo] varchar(8000) NULL, 
	[data_pool] varchar(8000) NULL, 
	[data_qty] bigint NULL, 
	[data_approvalStatus] varchar(8000) NULL, 
	[data_statusApprovalIAMIFrom] varchar(8000) NULL, 
	[data_statusApprovalIAMITo] varchar(8000) NULL, 
	[data_deviceNo] varchar(8000) NULL, 
	[data_crossRegion] varchar(8000) NULL, 
	[data_receiptDate] varchar(8000) NULL, 
	[data_shipDate] varchar(8000) NULL, 
	[data_areaCodeFrom] varchar(8000) NULL, 
	[data_areaCodeTo] varchar(8000) NULL, 
	[data_fromSiteCode] varchar(8000) NULL, 
	[data_toSiteCode] varchar(8000) NULL, 
	[data_fromSiteName] varchar(8000) NULL, 
	[data_toSiteName] varchar(8000) NULL, 
	[data_fromWarehouse] varchar(8000) NULL, 
	[data_toWarehouse] varchar(8000) NULL
);