CREATE TABLE [dbo].[sparepart_purchaseOrderPart] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_vendorNo] varchar(8000) NULL, 
	[data_vendorName] varchar(8000) NULL, 
	[data_address] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_poNo] varchar(8000) NULL, 
	[data_poDate] varchar(8000) NULL, 
	[data_poType] varchar(8000) NULL, 
	[data_site] varchar(8000) NULL, 
	[data_items_warehouse] varchar(8000) NULL, 
	[data_items_itemNo] varchar(8000) NULL, 
	[data_items_productName] varchar(8000) NULL, 
	[data_items_qty] bigint NULL, 
	[data_items_unitPrice] float NULL, 
	[data_poStatus] varchar(8000) NULL, 
	[data_items_itemGroup] varchar(8000) NULL, 
	[data_pool] varchar(8000) NULL, 
	[data_items_flagDeletion] bigint NULL, 
	[data_invoiceNo] varchar(8000) NULL, 
	[data_items_salesOrderNo] varchar(8000) NULL, 
	[data_items_discount] float NULL, 
	[data_items_netAmount] float NULL
);