CREATE TABLE [dbo].[sparepart_salesOrder] (

	[page] bigint NULL, 
	[rqUuid] varchar(8000) NULL, 
	[totalRows] bigint NULL, 
	[data_timestamp] varchar(8000) NULL, 
	[data_customerAccount] varchar(8000) NULL, 
	[data_name] varchar(8000) NULL, 
	[data_address] varchar(8000) NULL, 
	[data_salesOrderNo] varchar(8000) NULL, 
	[data_transactionNo] varchar(8000) NULL, 
	[data_tipeSO] varchar(8000) NULL, 
	[data_site] varchar(8000) NULL, 
	[data_items_warehouse] varchar(8000) NULL, 
	[data_items_itemNo] varchar(8000) NULL, 
	[data_items_productName] varchar(8000) NULL, 
	[data_items_qty] bigint NULL, 
	[data_items_uom] varchar(8000) NULL, 
	[data_items_unitPrice] bigint NULL, 
	[data_salesOrderStatus] varchar(8000) NULL, 
	[data_items_itemGroup] varchar(8000) NULL, 
	[data_pool] varchar(8000) NULL, 
	[data_items_flagDeletion] bigint NULL, 
	[data_items_reject] varchar(8000) NULL, 
	[data_cancellationReason] varchar(8000) NULL, 
	[data_items_invoiceNo] varchar(8000) NULL, 
	[data_createdTime] varchar(8000) NULL, 
	[data_lastModifiedTime] varchar(8000) NULL
);