CREATE TABLE [dbo].[CaseOprTable] (

	[Area] varchar(8000) NULL, 
	[Blocked] varchar(8000) NULL, 
	[Created] varchar(8000) NULL, 
	[CreatedDate] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[Description] varchar(8000) NULL, 
	[ExpirationDate] datetime2(6) NULL, 
	[ExternalCode] varchar(8000) NULL, 
	[Function] varchar(8000) NULL, 
	[Hours] float NULL, 
	[Modified] varchar(8000) NULL, 
	[ModifiedDate] datetime2(6) NULL, 
	[OprCategoryId] varchar(8000) NULL, 
	[OprId] varchar(8000) NULL, 
	[OprLinePropertyId] varchar(8000) NULL, 
	[OprRelation] varchar(8000) NULL, 
	[OprRelationCode] varchar(8000) NULL, 
	[ProjCategoryId] varchar(8000) NULL, 
	[ProjLinePropertyId] varchar(8000) NULL, 
	[RuleType] varchar(8000) NULL, 
	[StandardHours] varchar(8000) NULL, 
	[SubFunction] varchar(8000) NULL, 
	[Txt] varchar(8000) NULL, 
	[UnitId] varchar(8000) NULL, 
	[ValidFromDate] datetime2(6) NULL, 
	[ValidToDate] datetime2(6) NULL, 
	[Last_Update] datetime2(6) NULL
);