CREATE TABLE [dbo].[CaseJoblistHour] (

	[CancelDate] datetime2(6) NULL, 
	[Created] varchar(8000) NULL, 
	[CreatedDate] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[FinishDate] datetime2(6) NULL, 
	[Hours] float NULL, 
	[HoursMultiplier] float NULL, 
	[JobListId] varchar(8000) NULL, 
	[JobListTransId] varchar(8000) NULL, 
	[JobListTransIdRef] varchar(8000) NULL, 
	[LineAmount] float NULL, 
	[LineNum] float NULL, 
	[MainOprId] varchar(8000) NULL, 
	[Modified] varchar(8000) NULL, 
	[ModifiedDate] datetime2(6) NULL, 
	[OprCategoryId] varchar(8000) NULL, 
	[OprId] varchar(8000) NULL, 
	[OprLinePropertyId] varchar(8000) NULL, 
	[Origin] varchar(8000) NULL, 
	[OverrideStandardHours] varchar(8000) NULL, 
	[ProjCategoryId] varchar(8000) NULL, 
	[ProjLinePropertyId] varchar(8000) NULL, 
	[SalesPrice] float NULL, 
	[StartDate] datetime2(6) NULL, 
	[TriggerOnCase] varchar(8000) NULL, 
	[TriggerOnClaimInbound] varchar(8000) NULL, 
	[TriggerOnClaimOutbound] varchar(8000) NULL, 
	[Txt] varchar(8000) NULL, 
	[WrkCtrCapability_Name] varchar(8000) NULL, 
	[Last_Update] datetime2(6) NULL
);