CREATE TABLE [dbo].[MRPDemand_202302] (

	[CreatedDateTimeHeader] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[DataAreaIdHeader] varchar(8000) NULL, 
	[MonthsInNumb] int NULL, 
	[NoUrut] float NULL, 
	[RecordIDHeader] bigint NULL, 
	[ZAccumulation] float NULL, 
	[ZAccumulationPct] float NULL, 
	[ZCountDemand] float NULL, 
	[ZCountDemandAvg] float NULL, 
	[ZCountDemandPrev01] float NULL, 
	[ZCountDemandPrev02] float NULL, 
	[ZCountDemandPrev03] float NULL, 
	[ZCountDemandPrev04] float NULL, 
	[ZCountDemandPrev05] float NULL, 
	[ZDemandMonth] varchar(8000) NULL, 
	[ZDemandYear] int NULL, 
	[ZInventLocationId] varchar(8000) NULL, 
	[ZInventSiteId] varchar(8000) NULL, 
	[ZItemId] varchar(8000) NULL, 
	[ZMRPABCCode] varchar(8000) NULL, 
	[ZMRPDemandHeader] bigint NULL, 
	[ZMRPForecastID] varchar(8000) NULL, 
	[ZQtyDemand] float NULL, 
	[ZQtyDemandPrev01] float NULL, 
	[ZQtyDemandPrev02] float NULL, 
	[ZQtyDemandPrev03] float NULL, 
	[ZQtyDemandPrev04] float NULL, 
	[ZQtyDemandPrev05] float NULL, 
	[ZRank] int NULL, 
	[ZTransDate] datetime2(6) NULL
);