CREATE TABLE [dbo].[MRPSuggestionOrder] (

	[AgitClassPart] varchar(8000) NULL, 
	[AgitPurchasePrice] float NULL, 
	[AgitReason] varchar(8000) NULL, 
	[AgitSugestionOrderQty] float NULL, 
	[AgitTotalAmount] float NULL, 
	[CreatedDateTimeHeader] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[DataAreaIdHeader] varchar(8000) NULL, 
	[FD] float NULL, 
	[RecIdHeader] bigint NULL, 
	[ZAMItemMajorGroupId] varchar(8000) NULL, 
	[ZDate] datetime2(6) NULL, 
	[ZDStockLevel] float NULL, 
	[ZInventLocationId] varchar(8000) NULL, 
	[ZInventSiteId] varchar(8000) NULL, 
	[ZInventTransId] varchar(8000) NULL, 
	[ZItemId] varchar(8000) NULL, 
	[ZItemName] varchar(8000) NULL, 
	[ZMRPDemandNormalizedHeader] bigint NULL, 
	[ZMRPForecastID] varchar(8000) NULL, 
	[ZMRPSuggestionOrderId] varchar(8000) NULL, 
	[ZNumOfLines] int NULL, 
	[ZOnHand] float NULL, 
	[ZOnOrder] float NULL, 
	[ZOrderQty] float NULL, 
	[ZPrimaryVendorId] varchar(8000) NULL, 
	[ZPurchId] varchar(8000) NULL
);