CREATE TABLE [dbo].[Report_34] (

	[Customer_ID] varchar(8000) NULL, 
	[Customer_Name] varchar(8000) NULL, 
	[SO/PKB_no] varchar(8000) NULL, 
	[PKB_no] varchar(8000) NULL, 
	[SalesOrderPoolId] varchar(8000) NULL, 
	[InvoiceId] varchar(8000) NULL, 
	[SO/PKB_Date] varchar(8000) NULL, 
	[Tipe] varchar(8000) NULL, 
	[ItemGroupId] varchar(8000) NULL, 
	[Part_number] varchar(8000) NULL, 
	[Part_Name] varchar(8000) NULL, 
	[SalesQty] float NULL, 
	[QTY] float NULL, 
	[Amount] float NULL, 
	[Invoice_Date] varchar(8000) NULL, 
	[Kode_Dealer] varchar(8000) NULL, 
	[Dealer] varchar(8000) NULL, 
	[Kode_Outlet] varchar(8000) NULL, 
	[Outlet] varchar(8000) NULL, 
	[Area] varchar(8000) NULL, 
	[Remarks] varchar(8000) NULL, 
	[LastUpdate] datetime2(6) NULL, 
	[DealerCategory] varchar(8000) NULL, 
	[MaskingName] varchar(8000) NULL, 
	[FlagDelete] varchar(8000) NULL, 
	[RecordId] bigint NULL
);