CREATE TABLE [dbo].[Report_30_20230510] (

	[nama_dealer_billing_sap] varchar(8000) NULL, 
	[kode_dealer_billing_sap] varchar(8000) NULL, 
	[nomor_billing_sap] varchar(8000) NULL, 
	[Reference_Doc] varchar(8000) NULL, 
	[ISCanceled] varchar(8000) NULL, 
	[tanggal_billing_sap] datetime2(6) NULL, 
	[tanggal_terima_atau_tanggal_gr_dealer] datetime2(6) NULL, 
	[gr_fisik] int NULL, 
	[kode_dealer_gr] varchar(8000) NULL, 
	[nama_dealer_gr] varchar(8000) NULL, 
	[nama_dealer_posisi_stock_unit] varchar(8000) NULL, 
	[kode_dealer_posisi_stock_unit] varchar(8000) NULL, 
	[outlet] varchar(8000) NULL, 
	[area] varchar(8000) NULL, 
	[major_group] varchar(8000) NULL, 
	[types] varchar(8000) NULL, 
	[device_class] varchar(8000) NULL, 
	[model] varchar(8000) NULL, 
	[material_description_sap] varchar(8000) NULL, 
	[chassis_number] varchar(8000) NULL, 
	[engine_number] varchar(8000) NULL, 
	[kode_warna] varchar(8000) NULL, 
	[color_desc] varchar(8000) NULL, 
	[Stock_Qty] int NULL, 
	[reserved] int NULL, 
	[nomer_so] varchar(8000) NULL, 
	[tanggal_so] datetime2(6) NULL, 
	[nama_customer] varchar(8000) NULL, 
	[Status] varchar(8000) NULL, 
	[last_process] datetime2(6) NULL, 
	[tanggal_delivery_out_pdc] datetime2(6) NULL, 
	[Last_Update] varchar(8000) NULL
);