CREATE TABLE [dbo].[temp_AGITEFakpol] (

	[IdFakpol] varchar(8000) NULL, 
	[DealerCategory] varchar(8000) NULL, 
	[KodeOutlet] varchar(8000) NULL, 
	[OutletName] varchar(8000) NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[InvoiceNo] varchar(8000) NULL, 
	[CustomerName] varchar(8000) NULL, 
	[KTP] varchar(8000) NULL, 
	[TDP] varchar(8000) NULL, 
	[Alamat] varchar(8000) NULL, 
	[City] varchar(8000) NULL, 
	[TanggalPengajuanFakpol] datetime2(6) NULL, 
	[NoPengajuanFakpol] varchar(8000) NULL, 
	[CreatedDate] datetime2(6) NULL, 
	[ApprovalDate] datetime2(6) NULL, 
	[PrintedDate] datetime2(6) NULL, 
	[TglFakpol] datetime2(6) NULL, 
	[NoFakpol] varchar(8000) NULL, 
	[StatusFakpol] varchar(8000) NULL, 
	[NamaFakpol] varchar(8000) NULL, 
	[AlamatFakpol] varchar(8000) NULL, 
	[CityFakpol] varchar(8000) NULL, 
	[KecamatanFakpol] varchar(8000) NULL, 
	[KelurahanFakpol] varchar(8000) NULL, 
	[KodePosFakpol] varchar(8000) NULL, 
	[Email] varchar(8000) NULL, 
	[Color] varchar(8000) NULL, 
	[ChassisNumber] varchar(8000) NULL, 
	[Engine_Number] varchar(8000) NULL
);