CREATE TABLE [dbo].[ZMRPDemandLiness] (

	[CreatedDateTime1] datetime2(6) NULL, 
	[dataAreaId] varchar(8000) NULL, 
	[NoUrut] float NULL, 
	[RecordId] bigint NULL, 
	[ZAccumulation] float NULL, 
	[ZAccumulationPct] float NULL, 
	[ZCountDemand] float NULL, 
	[ZCountDemandAvg] float NULL, 
	[ZCountDemandPrev01] float NULL, 
	[ZCountDemandPrev02] float NULL, 
	[ZCountDemandPrev03] float NULL, 
	[ZCountDemandPrev04] float NULL, 
	[ZCountDemandPrev05] float NULL, 
	[ZInventLocationId] varchar(8000) NULL, 
	[ZInventSiteId] varchar(8000) NULL, 
	[ZItemId] varchar(8000) NULL, 
	[ZMRPABCCode] varchar(8000) NULL, 
	[ZMRPDemandHeader1] bigint NULL, 
	[ZQtyDemand] float NULL, 
	[ZQtyDemandPrev01] float NULL, 
	[ZQtyDemandPrev02] float NULL, 
	[ZQtyDemandPrev03] float NULL, 
	[ZQtyDemandPrev04] float NULL, 
	[ZQtyDemandPrev05] float NULL, 
	[ZRank] int NULL, 
	[Last_update] datetime2(6) NULL
);